#!/bin/bash

# 
# User options
mediadir="/home/mitch/Downloads/torrent/_anime"
destdir="/mnt/zed/media/anime/0 In Progress"

function postprocess {
    if [ "$(pwd)" != "$mediadir" ]; then
        # Not in root media dir don't move anything
        return
    fi

    # Remove from transmission
    if transmission-remote -l | grep -q -F "$1"; then
        id=$(transmission-remote -l | grep -F "$1" | awk '{ print $1 }')
        transmission-remote -t "$id" -r
    fi

    # regex in bash is hard... lets just not
    # Strip group
    name1=$(echo "$1" | sed 's|\[\S*\] ||')
    # Strip episode
    name2=$(echo "$name1" | sed 's| - [[:digit:]v\.]\+ .\+||')
    if [ "$name1" = "$name2" ]; then
        # No episode number found. Movie or OVA?
        name=""
    else
        # Title extracted
        name="$name2"
    fi

    if [ -d "${destdir}"/"${name}" ]; then 
        # echo "dest found"
        mv "$1" "${destdir}"/"${name}"
        # Reset last to account for moved file
        ((last--))
    else
        echo -ne "Target ${destdir}/${name} not found. Make it? (y/N) "
        read -r selection
        case $selection in
            y|Y)
                mkdir "${destdir}"/"${name}"
                mv "$1" "${destdir}"/"${name}"
                # Reset last to account for moved file
                ((last--))
            ;;
        esac
    fi


}

# shellcheck source=mediatree
source "$(dirname "$0")/mediatree" "${mediadir}"
