#!/bin/bash
IFS="\n"

getimage() {

    if [ -f .realname ]; then
        name=$(cat .realname)
    else
        name=$(pwd | awk -F/ '{ print $(NF) }')
    fi

    if [[ $name == Season* ]]; then
        name=$(pwd | awk -F/ '{ print $(NF-1) " " $(NF) }')
    fi

    html=$(curl -s -G --data-urlencode "q=$name" https://myanimelist.net/anime.php)

    echo "$name"
    # Check for exact match
    if echo "$html" | grep -q "<strong>$name</strong>"; then
        echo "Exact name found"
        image=$(echo "$html" | grep -B 10 "<strong>$name</strong>" | grep 100x140 | \
            sed 's|.*https://|https://|' | sed 's|?.*||' | sed 's|/r/100x140||')
    else
        echo "Using first search result"
        image=$(echo "$html" | grep 100x140 | grep -v Special | grep -v OVA | head -n1 | \
            sed 's|.*https://|https://|' | sed 's|?.*||' | sed 's|/r/100x140||')
    fi
    # echo "$image"

    convert "$image" .folder.png

    printf "[Desktop Entry]\nIcon=./.folder.png\n" > .directory
    echo ""
}


base=$(pwd)
if [ "$1" == "all" ]; then
    for x in *; do
        if [ ! -f "$base/$x"/.directory ]; then
            cd "$base/$x"
            getimage
        fi
    done
else
    getimage
fi
