#!/bin/bash

backup_zero() {
	if ping -c1 zero > /dev/null; then
		echo "doing zero"
		rsync -rtlP --info=progress2 --delete --exclude={/.\*,/VirtualBox\ VMs/,/gw2/} ~/ zero:ginger-backup
	else
		echo "zero not connected, skipping"
	fi
}

backup_ipod() {
	if lsusb | grep -q Apple; then
		echo "doing ipod"
		tcprelay.py -t 22:2222 &
		sleep 1
		rsync -rtlP --delete --exclude={/.\*,/VirtualBox\ VMs/,/Music/,/Downloads/} ~/ localipod:GingerBak/
		rsync -rtlP --delete ~/Music/* localipod:Music/
		sleep 1
		pkill tcprelay.py
	else
		echo "iPod not connected, skipping"
	fi

}

backup_bigdrive() {
	if `mount | grep -q '/mnt/bigdrive' || mount /mnt/bigdrive 2> /dev/null`; then
		echo "doing bigdrive"
		encfs -i 1 --extpass='gpg -o - --batch /mnt/bigdrive/ginger-key.asc' /mnt/bigdrive/ginger-enc /mnt/bigdrive/ginger
		if `mount | grep -q '/mnt/bigdrive/ginger'`
		then
			echo "encfs opened"
			rsync -rtP --delete --exclude={/.\*,/VirtualBox\ VMs/,/Music/,/Downloads/,/gw2/} ~/ /mnt/bigdrive/ginger/
			find ~/Music | sort > /mnt/bigdrive/ginger/music-list
			sleep 2
			fusermount -u /mnt/bigdrive/ginger
		else
			echo "Error opening encfs"
		fi
	else
		echo "bigdrive not connected, skipping"
	fi
	
	mount | grep -q '/mnt/bigdrive' && sleep 3s && umount /mnt/bigdrive 2> /dev/null
}

backup_local() {
	if [ -d /mnt/storage/backup ]; then
		echo "doing local"
		rsync -rtlP --delete --exclude={/.\*,/VirtualBox\ VMs/} ~/ /mnt/storage/backup
	else
		echo "local backup not mounted, skipping"
	fi
}

case $1 in
	"zero")
		backup_zero
		;;
	"ipod")
		backup_ipod
		;;
	"bigdrive")
		backup_bigdrive
		;;
	"local")
		backup_local
		;;
	"all")
		backup_zero
		backup_ipod
		backup_bigdrive
		backup_local
		;;
	*)
		echo "Specify target: zero, ipod, local, all"
esac 
