#!/bin/bash

if `mount | grep -q '/mnt/bigdrive' || mount /mnt/bigdrive`
then
	echo "mounted bigdrive"
	encfs -i 1 --extpass='gpg -o - --batch /mnt/bigdrive/ginger-key.asc' /mnt/bigdrive/ginger-enc /mnt/bigdrive/ginger
	if `mount | grep -q '/mnt/bigdrive/ginger'`
	then
		echo "encfs opened"
		rsync -rtP --delete --exclude={/Videos/,/Music/,/VirtualBox\ VMs/,openwrt/,/.\*} ~/ /mnt/bigdrive/ginger/
		find ~/Music | sort > /mnt/bigdrive/ginger/music-list
		sleep 2
		fusermount -u /mnt/bigdrive/ginger
	else
		echo "Error opening encfs"
	fi
else
	echo "Error mounting bigdrive"
fi