#!/bin/bash

NCPU=$(grep -c ^processor /proc/cpuinfo)
# Save 1 thread for system
NPROC=$(((NCPU)-1))
# min  2 threads
NPROC=$((NPROC>2 ? NPROC : 2))

COMMAND="optipng"
if [ "$1" == "--webp" ]; then
    COMMAND="to-webp --rm"
    shift
fi

WORKINGDIR=$(mktemp -d)
CBZ=$(readlink -f "$1")

cd "$WORKINGDIR"
unzip "$CBZ" > /dev/null
BEFORE=$(ls -lh "$CBZ")

find . -name '*.png' | \
    nice parallel -j "${NPROC}" -I% --max-args 1 --bar ${COMMAND} "%" > /dev/null

if command -v jpegoptim; then
    find . \( -iname '*.jpeg' -or -iname '*.jpg' \) | \
        nice parallel -j "${NPROC}" -I% --max-args 1 --bar jpegoptim "%" > /dev/null
fi

rm "$CBZ"
zip -0 "$CBZ" -- * > /dev/null

echo "$BEFORE"
ls -lh "$CBZ"

rm -r "$WORKINGDIR"