#!/bin/bash

CACHE_EXCLUDE=".*/\(borg\|thumbnails\|pacaur\|ccache\|yay\)"

# Kill browsers
echo "Closing browsers"
pgrep chromium && pkill --oldest chromium > /dev/null
pgrep chrome   && pkill --oldest chrome   > /dev/null
pgrep firefox  && pkill --oldest firefox  > /dev/null
sleep 1

# Clean downloads folder
echo "Cleaning downloads"
compgen -G ~/Downloads/\*.nzb     > /dev/null && rm ~/Downloads/*.nzb
compgen -G ~/Downloads/\*.torrent > /dev/null && rm ~/Downloads/*.torrent

# Clear cache
echo "Clearing cache"
find ~/.cache -maxdepth 1 -not -path ~/.cache -not -regex "$CACHE_EXCLUDE" -print0 | xargs -0 rm -r
[ -f ~/compose-cache/* ] && rm ~/.compose-cache/*

# Compact browser databases
echo "Compacting browser databases"
profile-cleaner


