#!/bin/sh

sudo mkdir -p /usr/local/share/zsh/site-functions/
sudo cp /usr/share/zsh/site-functions/_yay /usr/local/share/zsh/site-functions/_yay
sudo sed -i 's|yay -Pc|pacman -Sql|' /usr/local/share/zsh/site-functions/_yay
