#!/usr/bin/env python3

import urllib.request
import re
import os

user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'
headers = {'User-Agent': user_agent}

latest_url = "http://horriblesubs.info/lib/latest.php?nextid={0}"
search_url = "http://horriblesubs.info/lib/search.php?value={0}&nextid={1}"
# extract_regex = "<div class=\"episode\".+?>(.+?)<.+?id=720p.+?<i>(.+?)</i>.+?\"(magnet.+?)\""
extract_regex = "<i>([^<]+?\[720p\])<\/i>.+?\"(magnet:.+?)\""
add_command = "transmission-remote zero:9091 -a '{0}' > /dev/null"


class MODE:
    LATEST = 0
    SEARCH = 1


def get_latest(page=0):
    request = urllib.request.Request(latest_url.format(page), None, headers)
    data = urllib.request.urlopen(request)
    html = str(data.read())
    return re.findall(extract_regex, html)


def get_search(search, page=0):
    request = urllib.request.Request(search_url.format(page), None, headers)
    data = urllib.request.urlopen(request)
    html = str(data.read())
    return re.findall(extract_regex, html)


def add_magnet(magnet):
    os.system(add_command.format(magnet))

if __name__ == "__main__":
    search = ""
    page = 0
    mode = MODE.LATEST
    while True:
        results = get_latest(page) if mode == MODE.LATEST else get_search(search, page)
        print("--- {0} --- Page {1} ---".format("Latest" if mode == MODE.LATEST else search, page + 1))
        for i in range(0, len(results)):
            print("{0:02d}) {1}".format(i+1, results[i][0]))
        try:
            s = input('--> ')
        except:
            break
        if s == "":
            page = page + 1
        elif s == ":p":
            if page >= 1:
                page = page - 1
        elif s == ":l":
            page = 0
            mode = MODE.LATEST
        elif s.split(' ')[0].isdigit():
            toget = s.split(' ')
            for x in toget:
                if x.isdigit() and int(x) >= 1 and int(x) <= len(results):
                    add_magnet(results[int(x)-1][1])
        elif s.split('-')[0].isdigit() and s.split('-')[1].isdigit():
            toget = s.split('-')
            for x in range(int(toget[0]), int(toget[1]), 1 if int(toget[0]) < int(toget[1]) else -1):
                add_magnet(results[int(x)-1][1])
            add_magnet(results[int(toget[1])-1][1])
        else:
            search = s
            mode = MODE.SEARCH
