#!/bin/bash

# 
# User options
mediadir="/mnt/zed/media"
playercmd="mpv"
playerargs=""
fileregex=".*\(avi\|mkv\|flv\|mp4\|m4v\)"

bold="\033[1m"
green=$(tput setaf 2)
blue=$(tput setaf 4)
white=$(tput setaf 7)
normal=$(tput sgr0)

cd "$mediadir"
last=0

while true; do

	mapfile -t list_dirs  < <(find . -maxdepth 1 -type d -regex "\./[^.].*"  | sed 's|./||' | sort)
	mapfile -t list_files < <(find . -maxdepth 1 -type f -regex "$fileregex" | sed 's|./||' | sort)

	list_merged=("${list_dirs[@]}" "${list_files[@]}")
	digits=$(echo -n ${#list_merged[@]} | wc -m)
	f=0
	printf "${bold}----(${blue}%s${white})----${normal}\n" "$(pwd | awk -F/ '{print $NF}')"

	printf "${bold}%${digits}i. ${blue}%s${normal}\n" 0 ".."
	for dir in "${list_dirs[@]}"; do
		printf "${bold}%${digits}i. ${blue}%s${normal}\n" $((++f)) "$dir"
	done
	for file in "${list_files[@]}"; do
		printf "${bold}%${digits}i. ${green}%s${normal}\n" $((++f)) "$file"
	done
	echo -ne "> "
	read -r selection

	case $selection in
		"0" | ".." | ".")
			if [ "$(pwd)" != "$mediadir" ]; then 
				cd ..
			fi
			;;
		*)
			if [ "$selection" == "n" ]; then
				selection=$last
				((selection++))
			fi
			if [ -d "${list_merged[(selection-1)]}" ]; then
				cd "${list_merged[(selection-1)]}"
				last=0
			else
				${playercmd} ${playerargs} "${list_merged[(selection-1)]}"
				last=$selection
			fi
			;;
	esac
done
