#!/bin/bash

# 
# User options
musicdir="/home/mitch/Music"
playercmd="mpv"
playerargs="--no-video"
fileregex=".*\(mp3\|flac\|mp4\|m4a\|wma\|wav\)"


bold=$(tput bold)
green=$(tput setaf 2)
blue=$(tput setaf 4)
white=$(tput setaf 7)
normal=$(tput sgr0)

cd "$musicdir"

play_folder() {
	mapfile -t files < <(find . -maxdepth 1 -type f -regex "$fileregex" | sed 's|./||' | sort)
	if [ ${#files[@]} -ne 0 ]; then
		for file in "${files[@]}"; do
			printf "${bold}${green}%s\n" "$file"
		done
		$playercmd $playerargs "${files[@]}"
	fi
}

while true; do
	mapfile -t list < <(find . -maxdepth 1 -type f -regex "$fileregex" | sed 's|./||' | sort)
	digits=$(echo -n ${#list[@]} | wc -m)
	f=0
	printf "${bold}----(${blue}%s${white})----${normal}\n" "$(pwd | awk -F/ '{print $NF}')"

	printf "${bold}%${digits}i. ${blue}%s${normal}\n" 0 ".."
	for dir in "${list[@]}"; do
		printf "${bold}%${digits}i. ${blue}%s${normal}\n" $((++f)) "$dir"
	done
	if [ ! -z "$(find . -maxdepth 1 -type f -regex "$fileregex")" ]; then
		printf "${bold}%${digits}s. ${green}Play all in ${white}%s${normal}\n" "p" "$(pwd)"
	fi
	echo -ne "> "
	read -r selection

	case $selection in
		"0" | "..")
			if [ "$(pwd)" != "$musicdir" ]; then 
				cd ..
			fi
			;;
		"p")
			play_folder
			;;
		*)
			cd "${list[(selection-1)]}"
			if [ "$(find . -maxdepth 1 -type d | wc -l)" -eq 1 ]; then
				play_folder
				cd ..
			fi
			;;
	esac
done
