#!/bin/sh

curl -4 https://ipv4.am.i.mullvad.net/ip &
#echo
curl -6 https://ipv6.am.i.mullvad.net/ip &
#echo
if ip a | grep 10.0.1.99 -q; then
    curl --interface 10.0.1.99 --connect-timeout 2 https://am.i.mullvad.net/connected &
fi
wait
