#!/bin/bash

if [ "$#" -lt 1 ]; then
    borg list /mnt/zed/backups/borg | cut -c1-$(stty size </dev/tty | cut -d' ' -f2) # Truncate to term width
    exit
fi

for x in "$@"; do
    borg delete -pvs /mnt/zed/backups/borg::"$x"
done
