#!/bin/bash

# Close chrome nicely
pgrep chromium && wmctrl -c "chromium"
pgrep chrome   && wmctrl -c "chrome"

sleep .5

if pgrep steam; then
	kill -9 "$(pgrep steam)"
fi

if pgrep kdeinit5; then
	qdbus-qt5 org.kde.ksmserver /KSMServer org.kde.KSMServerInterface.logout 0 1 1
else
	sudo /sbin/reboot
fi
