#!/bin/bash

SUDO=''
if (( EUID != 0 )); then
    SUDO='sudo'
fi

# testing. maybe fix keyboard on reboots?
if [ "$HOSTNAME" = "ginger" ]; then
    BUS=$(grep 0356 /sys/bus/usb/devices/*/idProduct | cut -d'/' -f 6 | cut -d'.' -f 1)
    echo "$BUS" | $SUDO tee /sys/bus/usb/drivers/usb/unbind > /dev/null
fi

if pgrep plasma; then
    qdbus org.kde.Shutdown /Shutdown logoutAndReboot
else
    $SUDO /sbin/reboot
fi

# Catch if kde hangs on shutdown
sleep 20
$SUDO /sbin/reboot
