#!/bin/bash

SUDO=''
if (( EUID != 0 )); then
    SUDO='sudo'
fi

if pgrep plasma && [ -f /usr/bin/qdbus6 ] ; then
    qdbus6 org.kde.Shutdown /Shutdown logoutAndReboot
else
    $SUDO /sbin/reboot
fi

# Catch if kde hangs on shutdown
sleep 20
$SUDO /sbin/reboot
