#!/bin/bash

blue='\e[0;34m'
NC='\e[0m'

sudo btrfs filesystem show

echo -e "${blue}archRoot${NC}"
btrfs filesystem df /

echo -e "${blue}archStorage${NC}"
btrfs filesystem df /mnt/storage

if grep -q /mnt/backup\ btrfs /proc/mounts; then
	echo -e "${blue}notRed${NC}"
	btrfs filesystem df /mnt/backup
fi

echo -e "${blue}zed${NC}"
zpool list zed
echo ""
zfs list -r zed

if zpool list backup > /dev/null 2>&1; then
	echo -e "${blue}backup${NC}"
	zpool list backup
	echo ""
	zfs list -r backup
fi
