#!/bin/bash

for FILE in "$@"; do
    ffmpeg -i "$FILE" -c copy "${FILE%.*}.mkv"
    touch -r "$FILE" "${FILE%.*}.mkv"
done

for FILE in "$@"; do
    ls -lh "$FILE" "${FILE%.*}.mkv"
    rm -i "$FILE"
done
