#!/bin/bash

NCPU=$(grep -c ^processor /proc/cpuinfo)

# cwebp in mt mode seems to use 2 threads
# Save 1 thread for system
NPROC=$(((NCPU / 2)-1))
# min  2 threads
NPROC=$((NPROC>2 ? NPROC : 2))

find . -iname "*.png" | nice parallel -j "${NPROC}" -I% --max-args 1 --bar to-webp --rm  "%" > /dev/null
find . -iname "*.tif" | nice parallel -j "${NPROC}" -I% --max-args 1 --bar to-webp --rm  "%" > /dev/null
