#!/bin/bash

LS='ls -lh'
if [ -f /usr/bin/lsd ]; then
    LS='lsd --icon=never -lh'
fi

# Shitty arg parsing
RM='rm -i'
case $1 in
    "--rm")
        RM="rm"
        shift
        ;;
esac

# Enable/disable multi-treading based on ENV
MT_ARG="-mt"
if [ "$MT" == "no" ]; then
    echo "disabling multi-threading"
    MT_ARG=""
fi

for FILE in "$@"; do
    if [ "${FILE##*.}" == "gif" ]; then
        ffmpeg -i "$FILE" -c:v libwebp -lossless 1 -loop 0 -compression_level 6 -quality 100 "${FILE%.*}.webp"
        # cwebp -lossless -z 9 -mt "$FILE" -o "${FILE%.*}.webp"
    else
        cwebp -lossless -z 9 "${MT_ARG}" "$FILE" -o "${FILE%.*}.webp"
    fi
    touch -r "$FILE" "${FILE%.*}.webp"
done

for FILE in "$@"; do
    ${LS} "$FILE" "${FILE%.*}.webp"
    if webpinfo -quiet "${FILE%.*}.webp"; then
        ${RM} "$FILE"
    else
        echo "Invalid webp file! Not deleting"
    fi
done
