#!/bin/bash

FILE=$(readlink -f "$1")

if [[ "${FILE##*.}" == "mkv" ]]; then
    mpv -loop "$FILE"
elif unzip -l "$FILE" | grep -q '\.jpg'; then
    # TODO: Detect framerate
    ffmpeg -framerate 30 -i "$FILE" -c:v mjpeg -c copy  -f matroska -| mpv -loop -
else
    echo "TODO: non-jpg ugoira"
fi