#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "w2x [noise] [scale] [image]"
    exit 0
fi

METHOD="noise_scale"
NOISE=$1
SCALE=$2
IMAGE=$3
TTA=$4

NOISE_CMD="-noise_level ${NOISE}"
NOISE_NAME="n${NOISE}_"
if [ "${NOISE}" == "0" ]; then
    METHOD="scale"
    NOISE_CMD=""
    NOISE_NAME=""
fi

SCALE_CMD="-scale ${SCALE}"
SCALE_NAME="x${SCALE}"
if [ "${SCALE}" == "1" ]; then
    METHOD="noise"
    SCALE_CMD=""
fi

TTA_CMD=""
if [ "${TTA}" == "1" ]; then
    TTA_CMD="-tta 1"
fi

OUT="${IMAGE%.*}_[${NOISE_NAME}${SCALE_NAME}].png"

waifu2x -m "${METHOD}" "${NOISE_CMD}" "${SCALE_CMD}" "${TTA_CMD}" -i "${IMAGE}" -o "${OUT}"
