#!/bin/bash

wallpaperdir="/home/mitch/Pictures/bg"
enableddir="/home/mitch/Pictures/bg/__current"

# Ensure consistant sorting
export LC_COLLATE="C"

shopt -s extglob
IFS=$'\n'

bold=$(tput bold)
green=$(tput setaf 2)
blue=$(tput setaf 4)
white=$(tput setaf 7)
normal=$(tput sgr0)

mode="all"


while true; do
    cd "$wallpaperdir"
    list_orig=($(find -type f | grep -v "\\.svg" | sort))
    list_num=${#list_orig[@]}
    list=()

    # Remove duplicate resolutions
    for (( i = 0; i < $list_num; i++ )); do
        # Next item has a 1080 suffix, skip this one
        if ([ $(($i+1)) -lt $list_num ] && [ "$(basename ${list_orig[$i]%.*})_1080" = "$(basename ${list_orig[$i+1]%.*})" ]); then
            continue
        else
            if ([ $mode = "all" ] || [ $mode = "enabled_only" ]) && [ -e "${enableddir}/$(basename ${list_orig[$i]})" ]; then
                list+=(${list_orig[$i]})
            fi
            if ([ $mode = "all" ] || [ $mode = "disabled_only" ]) && ! [ -e "${enableddir}/$(basename ${list_orig[$i]})" ]; then
                list+=(${list_orig[$i]})
            fi
        fi
    done


    digits=`echo -n ${#list[@]} | wc -m`
    f=0
    printf "${bold}----(${blue}%s${white})----${normal}\n" "`pwd | awk -F/ '{print $NF}'`"

    for file in "${list[@]}"; do
        if [ -e "${enableddir}/$(basename $file)" ]; then
            printf "${bold}%${digits}i. ${green}%s${normal}\n" $((++f)) "✓$file"
        else
            printf "${bold}%${digits}i. ${blue}%s${normal}\n" $((++f)) "$file"
        fi
    done

    echo -ne "> "
    read selection

    case $selection in
        "all")
            mode="all"
            ;;
        "eo")
            mode="enabled_only"
            ;;
        "do")
            mode="disabled_only"
            ;;
        p[0-9]*)
            # Preview file
            snum=${selection#"p"}
            sfile=${list[snum-1]}
            feh -. "$sfile"
            ;;
        [0-9]*)
            # Process selection
            sfile=${list[selection-1]}

            if [ -e "${enableddir}/$(basename $sfile)" ]; then
                # File exists, disable it
                echo "Disabling $sfile"
                rm "${enableddir}/$(basename $sfile)"
            else
                # Enable bg
                echo "Enabling $sfile"
                cd "$enableddir"
                ln -s ".$sfile" .
            fi
            sleep 1
            ;;
    esac
done
