#!/bin/bash

if [[ $EUID -eq 0 ]]; then
	echo "Don't run me as root"
	exit
fi

if [ ! -b /dev/disk/by-partlabel/backup ]; then
	echo "Backup drive not connected"
	exit
fi

case "$1" in
	"open")
		sudo cryptsetup open /dev/disk/by-partlabel/backup backup
		sudo zpool import backup
		;;
	"close")
		sudo zpool export backup
		sudo cryptsetup close backup
		;;
	"rsync")
		if [ -e /dev/disk/by-uuid/67b8a324-6891-4d3a-a76c-bf814b0ecff1 ]; then
			rsync -Pa --delete --delete-excluded \
				--exclude=media/movies \
				--exclude=media/tv \
				--exclude=working/android/sdk \
				--exclude=misc/androidsdk \
				--exclude=misc/vr \
				--exclude="media/anime/*/\[HorribleSubs\]*" \
				--exclude="media/anime/*/*/\[HorribleSubs\]*" \
				--exclude=media/torrent \
				--exclude=backups/borg \
				/mnt/zed/ /mnt/backup/
		else
			rsync -Pa --delete --delete-excluded \
				--exclude=media/movies \
				--exclude=media/tv \
				--exclude=working/android/sdk \
				--exclude=misc/androidsdk \
				--exclude=misc/vr \
				--exclude="media/anime/*/\[HorribleSubs\]*" \
				--exclude="media/anime/*/*/\[HorribleSubs\]*" \
				--exclude=media/torrent \
				/mnt/zed/ /mnt/backup/
		fi
		;;
esac

