#!/bin/bash

if [[ $EUID -eq 0 ]]; then
	echo "Don't run me as root"
	exit
fi

if [ ! -b /dev/disk/by-partlabel/backup ]; then
	echo "Backup drive not connected"
	exit
fi

case "$1" in
	"open")
		sudo cryptsetup open /dev/disk/by-partlabel/backup backup
		sudo zpool import backup
		;;
	"close")
		sudo zpool export backup
		sudo cryptsetup close backup
		;;
	"rsync")
		rsync -Pa --delete --delete-excluded \
			--exclude=media/movies \
			--exclude=media/tv \
			--exclude=working/android/sdk \
			/mnt/zed/ /mnt/backup/
		;;
esac

