"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:seg1)\
$os\
$username\
$hostname\
[](fg:seg1 bg:seg2)\
$directory\
[](fg:seg2 bg:seg3)\
$git_branch\
$git_status\
[](fg:seg3 bg:seg4)\
$python\
[](fg:seg4)\
[ ](none)\
"""

right_format = """
$status
"""

palette = '256color'

[palettes.256color]
def_fg = '7'
def_bg = '0'
seg1 = '90'
seg2 = '168'
seg3 = '216'
seg4 = '110'
seg5 = '30'
seg6 = '24'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:seg1"
style_root = "bg:seg1"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_symbol = '@'
style = "bg:seg1"
format = '[$ssh_symbol$hostname]($style)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:seg1"
disabled = true # Disabled by default

[directory]
style = "bg:seg2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


# Segment 3
[git_branch]
symbol = ""
style = "bg:seg3"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:seg3"
format = '[$all_status$ahead_behind ]($style)'


# Segment 4
[python]
symbol = '  '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bg:seg4"

# right
[status]
format = "[](fg:seg6)[$symbol$status](bg:seg6)[](fg:seg6)"
disabled = false
